### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by xll2001** [NetManAIOps/OpsEval-Datasets#1]
Good work! I'd like to use your evaluation set, but I have a few questions.
1. Could you make your prompt open source so that I can evaluate it on my own questions?
2. Have any results already been generated for different LLMs, such as ChatGPT?
3. Do you have any ready-to-use scripts for evaluating certain LLMs?

**Comment by NickLennonLiu** [comment]
We appreciate your recognition! The details of the prompt are currently in the paper, and we also plan to add them to the repository, which is in progress. At the same time, we are organizing the code and results, and these will be updated in the repository in the future.
