### ISSUE TITLE
Provide some python scripts for evaluating the OpsEval dataset. 

### ISSUE THREAD

**Issue by LanduRi** [NetManAIOps/OpsEval-Datasets#2]
This will make it easier to test our models on OpsEval, thanks.

**Comment by NickLennonLiu** [comment]
Thank you for your feedback and suggestion! We are currently reformatting our evaluation script and planning to open-source them in the upcoming months to enhance the transparency and reproducibility of OpsEval.

Currently, if you wish to test your model on OpsEval, feel free to contact us via email at chpei@cnic.cn. We can discuss the access methods for the model and the details of the evaluation.
